### ISSUE TITLE
FormRequest validations

### ISSUE THREAD

**Issue by gregorip02** [cerbero90/enum#1]
Is there a way to get FormRequest validations from an enum?

## Context

Enumerations are commonly used at the PHP code and database level, in addition, in the FormRequest an extra layer of validation is added before trying to store in the database.

In my projects I usually use validation:

```php
$request->validate(['status' => 'required|in:active,inactive']);
```

What is sought is to add a method to automate this based on the values/names of the enum.

## Possible implementation

A method like the following would be very useful.

```php
<?php

namespace App\Enums;

use Cerbero\Enum\Concerns\Enumerates;

enum StatusEnum: string {
    use Enumerates;

    case ACTIVE = 'active';
    case INACTIVE = 'inactive';
}

StatusEnum::rules(); // ['in:active,inactive']
StatusEnum::rules(['required']); // ['required', 'in:active,inactive']
StatusEnum::rulesFromNames(); // ['in:ACTIVE,INACTIVE']
```

Please let me know if there is a way to do this currently, if not please consider adding it to your package, I'm happy to send a PR if needed. Thank you

**Comment by gregorip02** [comment]
Closing the issue by linking to Laravel, I thought it was a package oriented to the framework.

**Comment by cerbero90** [comment]
Hey @gregorip02, thanks for your proposal :)

As you correctly pointed out, this package is framework agnostic 👍 

Also wanted to add that optionally in Laravel you can validate enum values with the built-in `Enum` rule:

```php
use Illuminate\Validation\Rules\Enum;
 
$request->validate([
    'status' => ['required', new Enum(StatusEnum::class)],
]);
```
